import { Cairo } from "next/font/google"; // Import Cairo font
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin", "arabic"], 
  weight: ["300", "400", "700"], 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${cairo.variable} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
